### ISSUE TITLE
no way to execute whois 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DannyCork/python-whois#11]
```
import whois

domain = whois.query('google.com')
print (domain.status)


output:
Traceback (most recent call last):
  File "/root/workspace/test1/src/pkg/w.py", line 1, in <module>
    import whois
  File "/root/workspace/test1/src/pkg/whois.py", line 2, in <module>
AttributeError: 'module' object has no attribute 'query'

OS CentOS 6.4
Python 2.6.6
```

Original issue reported on code.google.com by `voipcall...@gmail.com` on 27 Oct 2013 at 7:20

**Comment by DannyCork** [comment]
You need to install the pip package whois not python-whois.

**Comment by Hryts** [comment]
I have tried installing both: whois and python-whois but none of them worked for me.
I found out that the issue is quite common but did not manage to find a fix for it.
If anyone succeeds, please share the solution
