### ISSUE TITLE
Missing regex for .com registrant

### ISSUE THREAD

**Issue by nayssaj** [DannyCork/python-whois#114]
There seems to be a missing regex for registrant parsing for .com TLD.

My suggestion would be to add the following regex : 
Registrant\s*Organi(?:s|z)ation:\s?(.+)

If the fix is ok I can make the corresponding pull request.
Also, is there any reasons why there's no distinction between the registrant org and the registrant name ?

**Comment by DannyCork** [comment]
please go ahead with the pr.

Not sure why there is no distinction.

**Comment by nayssaj** [comment]
I made a corresponding PR

I noticed that the registrant was not an attribute of the _Domain_ class that is returned by the module :
https://github.com/DannyCork/python-whois/blob/17341d07c4b68b9f207e04982d9632bcca0b0ed4/whois/_3_adjust.py#L9

In order to benefit from the registrant regexes, a new member attribute should be added. Otherwise all theses changes seems to be invisible to end users.
