### ISSUE TITLE
Error when trying to get registrar info.

### ISSUE THREAD

**Issue by aionet** [DannyCork/python-whois#116]
When testing various domains, I noticed that a bunch of the results do not return the registrar information and throw an error

  File "test.py", line 4, in <module>
    domain = whois.query('etecnics.com')
  File "/usr/local/lib/python3.7/dist-packages/whois/__init__.py", line 54, in query
    return Domain(pd) if pd['domain_name'][0] else None
  File "/usr/local/lib/python3.7/dist-packages/whois/_3_adjust.py", line 15, in __init__
    self.expiration_date        = str_to_date(data['expiration_date'][0])
  File "/usr/local/lib/python3.7/dist-packages/whois/_3_adjust.py", line 85, in str_to_date
    try: return datetime.datetime.strptime(s, format)
  File "/usr/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.7/_strptime.py", line 462, in _strptime
    if z[3] == ':':
IndexError: string index out of range

A sample domain I tested is etecnics.com (this is a valid domain)

**Comment by DannyCork** [comment]
works

```
>>> domain = whois.query('etecnics.com')
>>> print (domain.__dict__)
{'name': 'etecnics.com', 'registrar': 'DropCatch.com 528 LLC', 'registrant_country': 'US', 'creation_date': datetime.datetime(2020, 5, 24, 19, 8, 15), 'expiration_date': datetime.datetime(2021, 5, 24, 19, 8, 15), 'last_updated': datetime.datetime(2020, 5, 26, 23, 33, 38), 'status': 'clientTransferProhibited https://icann.org/epp#clientTransferProhibited', 'statuses': ['clientTransferProhibited https://icann.org/epp#clientTransferProhibited', 'clientTransferProhibited https://www.icann.org/epp#clientTransferProhibited'], 'dnssec': False, 'name_servers': {'nsg1.namebrightdns.com\r', 'nsg2.namebrightdns.com\r'}}
```

try the latest release
