### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified python-whois

### ISSUE THREAD

**Issue by Belgin-Android** [DannyCork/python-whois#123]
Information :
   --> Python - 3.8.2 
   --> Visual Studio Code
   --> installed by -- "pip install python-whois"
   --> Windows 10 64 Bit 

command line:  domain = whois.query('google.com')               

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\Python\lib\site-packages\whois\__init__.py", line 67, in query
    pd = do_parse(do_query(d, force, cache_file, slow_down, ignore_returncode), tld)
  File "G:\Python\lib\site-packages\whois\_1_query.py", line 46, in do_query
    _do_whois_query(dl, ignore_returncode),
  File "G:\Python\lib\site-packages\whois\_1_query.py", line 60, in _do_whois_query
    p = subprocess.Popen(['whois', '.'.join(dl)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "G:\Python\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "G:\Python\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by guediagael** [comment]
I have the same error

**Comment by Nilsbijlsma** [comment]
I had a very similar issue posted in my own issue-thread after Danny fixed the variable tz not being set in the else statement. He labeled it as a bug so I think he's aware of it. The only thing I can think of is reinstalling everything and trying it again. I don't think I use this in my project so I can't help you further.

**Comment by Belgin-Android** [comment]
No Reply From The Team : (

**Comment by Rain1971** [comment]
The problem is that you try this on windows. Windows has no whois tool on the system so you need to install sysinternals whois in your path to make it run
https://docs.microsoft.com/en-us/sysinternals/downloads/whois
capy whois.exe to your path. If you have windows 64 you need to rename whois64.exe and copy to your path.

This library calls whois and read the replay

https://github.com/DannyCork/python-whois/blob/2f75d1a079eac1738349564758c6678f5c406202/whois/_1_query.py#L60

**Comment by Nilsbijlsma** [comment]
> The problem is that you try this on windows. Windows has no whois tool on the system so you need to install sysinternals whois in your path to make it run
> https://docs.microsoft.com/en-us/sysinternals/downloads/whois
> capy whois.exe to your path. If you have windows 64 you need to rename whois64.exe and copy to your path.
> 
> This library calls whois and read the replay
> 
> https://github.com/DannyCork/python-whois/blob/2f75d1a079eac1738349564758c6678f5c406202/whois/_1_query.py#L60

To make my comment more clear, that was under Ubuntu 14.04 I believe and Python 2.7, not Windows (as opposed to the issue starter here).

**Comment by Rain1971** [comment]
> > The problem is that you try this on windows. Windows has no whois tool on the system so you need to install sysinternals whois in your path to make it run
> > https://docs.microsoft.com/en-us/sysinternals/downloads/whois
> > capy whois.exe to your path. If you have windows 64 you need to rename whois64.exe and copy to your path.
> > This library calls whois and read the replay
> > https://github.com/DannyCork/python-whois/blob/2f75d1a079eac1738349564758c6678f5c406202/whois/_1_query.py#L60
> 
> To make my comment more clear, that was under Ubuntu 14.04 I believe and Python 2.7, not Windows (as opposed to the issue starter here).

Under ubuntu you need to install whois using apt

sudo apt-get update
sudo apt-get install whois

on ubuntu 14.04

**Comment by Nilsbijlsma** [comment]
> > > The problem is that you try this on windows. Windows has no whois tool on the system so you need to install sysinternals whois in your path to make it run
> > > https://docs.microsoft.com/en-us/sysinternals/downloads/whois
> > > capy whois.exe to your path. If you have windows 64 you need to rename whois64.exe and copy to your path.
> > > This library calls whois and read the replay
> > > https://github.com/DannyCork/python-whois/blob/2f75d1a079eac1738349564758c6678f5c406202/whois/_1_query.py#L60
> > 
> > 
> > To make my comment more clear, that was under Ubuntu 14.04 I believe and Python 2.7, not Windows (as opposed to the issue starter here).
> 
> Under ubuntu you need to install whois using apt
> 
> sudo apt-get update
> sudo apt-get install whois
> 
> on ubuntu 14.04

Which was installed, as stated by the ReadMe.

**Comment by Belgin-Android** [comment]
Still It's Not Working

**Comment by DannyCork** [comment]
oh yes it is.

**Comment by emreekmekcioglu1** [comment]
I also had the same issue and I also add to PATH env. the whois by renaming it but it didn't work. So u can use a Virtual Machine with Ubuntu or u can use subprocess module and try to parse the output on your own  

> oh yes it is.

I also had the same issue and I also add to PATH env. the whois by renaming it but it didn't work. So u can use a Virtual Machine with Ubuntu or u can use subprocess module and try to parse the output on your own

**Comment by emreekmekcioglu1** [comment]
> I also had the same issue and I also add to PATH env. the whois by renaming it but it didn't work. So u can use a Virtual Machine with Ubuntu or u can use subprocess module and try to parse the output on your own
> 
> > oh yes it is.
> 
> I also had the same issue and I also add to PATH env. the whois by renaming it but it didn't work. So u can use a Virtual Machine with Ubuntu or u can use subprocess module and try to parse the output on your own

Or if u fpund out a way you can share :D
