### ISSUE TITLE
.info whois format changed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DannyCork/python-whois#13]
```
What steps will reproduce the problem?
>>> import whois
>>> w = whois.query('google.info')
>>> print w.__dict__
{'last_updated': None, 'name': 'google.info', 'expiration_date': None, 
'creation_date': None, 'registrar': 'MarkMonitor Inc. (R151-LRMS)', 
'name_servers': set(['ns3.google.com', 'name', 'ns1.google.com', 
'ns2.google.com', 'dnssec:unsigned', 'ns4.google.com'])}

What is the expected output? What do you see instead?
last_updated, expiration_date and creation_date should be populated instead of 
being set to None.


What version of the product are you using? On what operating system?

Debian 6.0.9

whois --version : Version 5.0.10.

pip show whois

---
Name: whois
Version: 0.7
Location: /usr/local/lib/python2.6/dist-packages
Patched with 12 issue https://code.google.com/p/python-whois/issues/detail?id=12

Please provide any additional information below.

Need to extend "info" section from org section after applying patch from issue 
12 on this project.

```

Original issue reported on code.google.com by `rodion....@gmail.com` on 25 Feb 2014 at 8:04

Attachments:
- [diff_tld_regexpr.diff](https://storage.googleapis.com/google-code-attachments/python-whois/issue-13/comment-0/diff_tld_regexpr.diff)

**Comment by DannyCork** [comment]
still an issue for .infos

**Comment by DannyCork** [comment]
.infos last_updated, expiration_date and creation_date  populated.

[](
>>> domain = whois.query('google.info')
>>> print(domain.__dict__)
{'name': 'google.info', 'registrar': 'MarkMonitor Inc.', 'registrant_country': 'US', 'creation_date': datetime.datetime(2001, 7, 31, 23, 57, 50), 'expiration_date': datetime.datetime(2021, 7, 31, 23, 57, 50), 'last_updated': datetime.datetime(2020, 6, 29, 9, 38, 8), 'status': 'clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited', 'statuses': ['clientTransferProhibited https://icann.org/epp#clientTransferProhibited', 'clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited', 'serverUpdateProhibited https://icann.org/epp#serverUpdateProhibited', 'serverDeleteProhibited (https://www.icann.org/epp#serverDeleteProhibited)', 'serverTransferProhibited https://icann.org/epp#serverTransferProhibited', 'clientUpdateProhibited (https://www.icann.org/epp#clientUpdateProhibited)', 'clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited', 'clientTransferProhibited (https://www.icann.org/epp#clientTransferProhibited)', 'serverUpdateProhibited (https://www.icann.org/epp#serverUpdateProhibited)', 'serverTransferProhibited (https://www.icann.org/epp#serverTransferProhibited)', 'serverDeleteProhibited https://icann.org/epp#serverDeleteProhibited', 'clientDeleteProhibited (https://www.icann.org/epp#clientDeleteProhibited)'], 'dnssec': False, 'name_servers': {'ns2.google.com', 'ns2.google.com\r', 'ns1.google.com\r', 'ns1.google.com', 'ns3.google.com\r', 'ns4.google.com\r', 'ns3.google.com', 'ns4.google.com'}}
>>>)
