### ISSUE TITLE
support for .vn ccTLD

### ISSUE THREAD

**Issue by nguyendan07** [DannyCork/python-whois#135]
Can you please add support for the .vn ccTLD?

Thanks!

**Comment by WKobes** [comment]
On hold, as there is no WHOIS server for .vn

```
This TLD has no whois server, but you can access the whois database at
http://www.vnnic.vn/en
```

**Comment by maarten-boot** [comment]
can be closed IMHO

is now solved with:
vn = {"extend": "_privateReg"}
