### ISSUE TITLE
whois.query('google.com') - Dont work

### ISSUE THREAD

**Issue by mavar** [DannyCork/python-whois#139]
Not working `whois.query('google.com') `.
 I have error: 
`
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-37-63ee5b68c664> in <module>()
      1 import whois
----> 2 domain = whois.query('google.com')
      3 domain

4 frames
/usr/local/lib/python3.6/dist-packages/whois/__init__.py in query(domain, force, cache_file, slow_down, ignore_returncode)
     65     >>> print(extract_domain('globoesporte.globo.com'))
     66     globo.com
---> 67     >>> print(extract_domain('1-0-1-1-1-0-1-1-1-1-1-1-1-.0-0-0-0-0-0-0-0-0-0-0-0-0-10-0-0-0-0-0-0-0-0-0-0-0-0-0.info'))
     68     0-0-0-0-0-0-0-0-0-0-0-0-0-10-0-0-0-0-0-0-0-0-0-0-0-0-0.info
     69     >>> print(extract_domain('2607:f8b0:4006:802::200e'))

/usr/local/lib/python3.6/dist-packages/whois/_1_query.py in do_query(dl, force, cache_file, slow_down, ignore_returncode)
     44         CACHE[k] = (
     45             int(time.time()),
---> 46             _do_whois_query(dl, ignore_returncode),
     47         )
     48         if cache_file:

/usr/local/lib/python3.6/dist-packages/whois/_1_query.py in _do_whois_query(dl, ignore_returncode)
     58         Linux 'whois' command wrapper
     59     """
---> 60     p = subprocess.Popen(['whois', '.'.join(dl)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
     61     r = p.communicate()[0]
     62     r = r.decode() if PYTHON_VERSION == 3 else r

/usr/lib/python3.6/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    727                                 c2pread, c2pwrite,
    728                                 errread, errwrite,
--> 729                                 restore_signals, start_new_session)
    730         except:
    731             # Cleanup if the child failed starting.

/usr/lib/python3.6/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1362                         if errno_num == errno.ENOENT:
   1363                             err_msg += ': ' + repr(err_filename)
-> 1364                     raise child_exception_type(errno_num, err_msg, err_filename)
   1365                 raise child_exception_type(err_msg)
   1366 

FileNotFoundError: [Errno 2] No such file or directory: 'whois': 'whois'
`

What is this?

**Comment by Dilshan1997** [comment]
yes, it is not working. what is reason

**Comment by Pherang** [comment]
Hi,

You may have to install the whois application on the computer you're running this on.

**Comment by DannyCork** [comment]
not an issue
```
$python
>>> import whois
>>> domain = whois.query('google.com')
>>> print (domain.__dict__)
```

`{'name': 'google.com', 'registrar': 'MarkMonitor Inc.', 'registrant_country': 'US', 'creation_date': datetime.datetime(1997, 9, 15, 4, 0), 'expiration_date': datetime.datetime(2028, 9, 14, 4, 0), 'last_updated': datetime.datetime(2019, 9, 9, 15, 39, 4), 'status': 'clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited', 'statuses': ['serverTransferProhibited https://icann.org/epp#serverTransferProhibited', 'clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited', 'serverUpdateProhibited https://icann.org/epp#serverUpdateProhibited', 'clientUpdateProhibited (https://www.icann.org/epp#clientUpdateProhibited)', 'clientDeleteProhibited (https://www.icann.org/epp#clientDeleteProhibited)', 'clientTransferProhibited https://icann.org/epp#clientTransferProhibited', 'serverUpdateProhibited (https://www.icann.org/epp#serverUpdateProhibited)', 'serverTransferProhibited (https://www.icann.org/epp#serverTransferProhibited)', 'clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited', 'serverDeleteProhibited https://icann.org/epp#serverDeleteProhibited', 'clientTransferProhibited (https://www.icann.org/epp#clientTransferProhibited)', 'serverDeleteProhibited (https://www.icann.org/epp#serverDeleteProhibited)'], 'dnssec': False, 'name_servers': {'ns3.google.com\r', 'ns1.google.com\r', 'ns2.google.com', 'ns2.google.com\r', 'ns3.google.com', 'ns1.google.com', 'ns4.google.com', 'ns4.google.com\r'}}
`
