### ISSUE TITLE
ValueError: Unknown date format

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DannyCork/python-whois#14]
```
What steps will reproduce the problem?

1. easy_install whois
Searching for whois
Reading http://pypi.python.org/simple/whois/
Best match: whois 0.7
Downloading 
https://pypi.python.org/packages/source/w/whois/whois-0.7.tar.gz#md5=01a31bcb0d0
fa3d02b7ea336a00fe4f4
Processing whois-0.7.tar.gz
Running whois-0.7/setup.py -q bdist_egg --dist-dir 
/tmp/easy_install-MbP61X/whois-0.7/egg-dist-tmp-0DuwM6
zip_safe flag not set; analyzing archive contents...
Adding whois 0.7 to easy-install.pth file

Installed /usr/lib/python2.6/site-packages/whois-0.7-py2.6.egg
Processing dependencies for whois
Finished processing dependencies for whois

2. # python
Python 2.6.6 (r266:84292, Jan 22 2014, 06:01:05) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import whois
>>> domain = whois.query('google.com')

What is the expected output? What do you see instead?

I see ValueError: Unknown date format: 


What version of the product are you using? On what operating system?
 cat /etc/redhat-release 
CloudLinux Server release 6.5 (Pavel Popovich) (It's clone CentOS 6.5)
Python 2.6.6 (r266:84292, Jan 22 2014, 06:01:05) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2

Please provide any additional information below.

 domain = whois.query('google.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/whois-0.7-py2.6.egg/whois/__init__.py", line 54, in query
    return Domain(pd) if pd['domain_name'][0] else None
  File "/usr/lib/python2.6/site-packages/whois-0.7-py2.6.egg/whois/_3_adjust.py", line 14, in __init__
    self.creation_date          = str_to_date(data['creation_date'][0])
  File "/usr/lib/python2.6/site-packages/whois-0.7-py2.6.egg/whois/_3_adjust.py", line 82, in str_to_date
    if PYTHON_VERSION < 3: return str_to_date_py2(s)
  File "/usr/lib/python2.6/site-packages/whois-0.7-py2.6.egg/whois/_3_adjust.py", line 100, in str_to_date_py2
    raise ValueError("Unknown date format: '%s'" % s)
ValueError: Unknown date format: '2002-10-02t00:00:00-0700'

```

Original issue reported on code.google.com by `eduar...@tech.namecheap.com` on 2 Apr 2014 at 11:00

**Comment by edgreenberg** [comment]
Is there any resolution to this? I have the same problem on Fedora 24 with Python 2.7

**Comment by neok0** [comment]
Quick and dirty fix: 
change this line in the _3_adjust.py file:
return datetime.datetime.strptime(s, format) + datetime.timedelta(hours=tz)
to 
return datetime.datetime.strptime(s.split("+")[0], format) + datetime.timedelta(hours=tz)

**Comment by pauliuszaleckas** [comment]
I am also having this exact problem

**Comment by dryicebomb** [comment]
also having this issue. 
>>> w = whois.query('ubuntu.org')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/whois/__init__.py", line 54, in query
    return Domain(pd) if pd['domain_name'][0] else None
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/whois/_3_adjust.py", line 15, in __init__
    self.expiration_date	= str_to_date(data['expiration_date'][0])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/whois/_3_adjust.py", line 93, in str_to_date
    raise ValueError("Unknown date format: '%s'" % s)
ValueError: Unknown date format: 'registrar: soluciones corporativas ip, sl'

**Comment by DannyCork** [comment]
> also having this issue.
> `w = whois.query('ubuntu.org')`
> 
> > Traceback
> 
> > (most recent call last):
> > File "", line 1, in 
> > File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/whois/**init**.py", line 54, in query
> > return Domain(pd) if pd['domain_name'][0] else None
> > File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/whois/_3_adjust.py", line 15, in **init**
> > self.expiration_date	= str_to_date(data['expiration_date'][0])
> > File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/whois/_3_adjust.py", line 93, in str_to_date
> > raise ValueError("Unknown date format: '%s'" % s)
> > ValueError: Unknown date format: 'registrar: soluciones corporativas ip, sl'
> 
> it seems to fail on all .org addresses

.org works
```
>>> print (w.__dict__)
{'name': 'ubuntu.org', 'registrar': 'DropCatch.com 1097 LLC', 'creation_date': None, 'expiration_date': datetime.datetime(2019, 8, 28, 14, 30, 34), 'last_updated': None, 'name_servers': {'ns1.parklogic.com\r', 'ns4.parklogic.com\r', 'ns3.parklogic.com\r', 'ns2.parklogic.com\r'}}
```
