### ISSUE TITLE
Element "expiration date" always None in .fr

### ISSUE THREAD

**Issue by p0lux** [DannyCork/python-whois#141]
Environnement : 
- Python : 3.7
- module whois version : 0.9.7

When i start some research about the expiration_date element, i get None all the time. 

https://google.fr 

`{'name': 'google.fr', 'registrar': 'MARKMONITOR Inc.', 'creation_date': datetime.datetime(2000, 7, 26, 22, 0), 'expiration_date': None, 'last_updated': datetime.datetime(2020, 11, 28, 10, 35, 1), 'status': 'ACTIVE', 'name_servers': {'ns2.google.com', 'ns3.google.com', 'ns1.google.com', 'ns4.google.com'}}`

https://bssi.fr

`{'name': 'bssi.fr', 'registrar': 'OVH', 'creation_date': datetime.datetime(2010, 9, 21, 10, 21, 42), 'expiration_date': None, 'last_updated': datetime.datetime(2020, 2, 2, 7, 34, 20), 'status': 'ACTIVE', 'name_servers': {'ns10.ovh.net', 'dns10.ovh.net'}}`

Someone can confirm? 

Thanks

**Comment by DannyCork** [comment]
```
>>> domain = whois.query('bssi.fr')
>>> print(domain.__dict__)
{'name': 'bssi.fr', 'registrar': 'OVH', 'registrant_country': '', 'creation_date': datetime.datetime(2010, 9, 21, 10, 21, 42), 'expiration_date': datetime.datetime(2022, 2, 2, 7, 9, 42), 'last_updated': datetime.datetime(2021, 2, 2, 7, 34, 54), 'status': 'ACTIVE', 'statuses': ['not identified', 'ACTIVE'], 'dnssec': False, 'name_servers': {'ns1-02.azure-dns.com', 'ns4-02.azure-dns.info', 'ns3-02.azure-dns.org', 'ns2-02.azure-dns.net'}}
```

working in the latest release.
