### ISSUE TITLE
Exception: Unknown TLD: ca

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DannyCork/python-whois#15]
```
$ cat a.py
import whois

domain = 'invisiblebracesintoronto.ca'
whois.query(domain, 'A')

$ python a.py
Exception: Unknown TLD: ca
(all known TLD: ['co', 'it', 'cz', 'at', 'eu', 'ru', 'lv', 'nz', 'net', 'pl', 
'be', 'fr', 'de', 'jp', 'me', 'co_jp', 'biz', 'org', 'info', 'name', 'us', 
'uk', 'com'])

```

Original issue reported on code.google.com by `sta...@wm4d.com` on 5 Oct 2014 at 4:21

**Comment by DannyCork** [comment]
Thanks for raising this.

Sadly, .ca isn't supported.It's on the todo list.

**Comment by nixawk** [comment]
```
# -*- coding: utf-8 -*-

import whois


new_tld = {
    'ca': {
        'creation_date': re.compile('Creation Date:\\s?(.+)', re.IGNORECASE),
        'domain_name': re.compile('Domain Name:\\s?(.+)', re.IGNORECASE),
        'emails': re.compile('[\\w.-]+@[\\w.-]+\\.[\\w]{2,4}', re.IGNORECASE),
        'expiration_date': re.compile('Expiration Date:\\s?(.+)', re.IGNORECASE),
        'name_servers': re.compile('Name Server:\\s*(.+)\\s*', re.IGNORECASE),
        'registrant': None,
        'registrar': re.compile('Registrar:\\s?(.+)', re.IGNORECASE),
        'status': re.compile('Domain Status:\\s?(.+)', re.IGNORECASE),
        'updated_date': re.compile('Updated Date:\\s?(.+)', re.IGNORECASE)
        }
    }

whois.TLD_RE.update(new_tld)


domain = 'invisiblebracesintoronto.ca'
print(whois.query(domain, 'A'))
```

**Comment by DannyCork** [comment]
.ca working
>>> import whois
>>> domain = whois.query('invisiblebracesintoronto.ca')
>>> print(domain.__dict__)
{'name': 'invisiblebracesintoronto.ca', 'registrar': 'Go Daddy Domains Canada, Inc', 'registrant_country': 'REDACTED FOR PRIVACY', 'creation_date': datetime.datetime(2013, 10, 4, 16, 27, 42), 'expiration_date': datetime.datetime(2021, 10, 4, 16, 27, 42), 'last_updated': datetime.datetime(2020, 11, 18, 16, 33, 19), 'status': 'clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited', 'statuses': ['clientTransferProhibited https://icann.org/epp#clientTransferProhibited', 'clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited', 'clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited'], 'dnssec': False, 'name_servers': {'dns1.stabletransit.com', 'dns2.stabletransit.com'}}
