### ISSUE TITLE
.com parsing fails for IANA domains

### ISSUE THREAD

**Issue by WKobes** [DannyCork/python-whois#152]
**Describe the bug**
Domains registered under .com by IANA directly output a different format, thus causes the parsing to fail. An example is `example.com`. Instead for regular format, it has the following output:

```
domain:       EXAMPLE.COM

organisation: Internet Assigned Numbers Authority

created:      1992-01-01
source:       IANA
```

**To Reproduce**
1. Query to example.com
2. Try to access `.__dict__`

**Expected behavior**
Should deal with the IANA format

**Comment by maarten-boot** [comment]
i think this is actually a side effect of the construct on _2_parse.py

    whois_splitted = whois_str.split("source:       IANA")
    if len(whois_splitted) == 2:
        whois_str = whois_splitted[1]
        
for example.com there is nothing after this line so the result is NONE
this is a special case

**Comment by maarten-boot** [comment]
should be fixed by pull request: #230

**Comment by maarten-boot** [comment]
i retracted #230 it introduced behaviour changes , reworking a new change set to handle this without introducing changes in the current behaviour, sorry for the confusion ;-)

**Comment by maarten-boot** [comment]
fixed now in https://github.com/DannyCork/python-whois/pull/233
