### ISSUE TITLE
.nl parsing of name servers fails due to IP addresses

### ISSUE THREAD

**Issue by WKobes** [DannyCork/python-whois#157]
**Describe the bug**
When a domain under .nl provides nameservers with IP addresses (when IPv6 is supported), the current regex fails. This results in no name servers returned.

**To Reproduce**
1. Example: `whois sidn.nl`

**Expected behavior**
Regex should be updated to ignore the IP addresses. Note that IPv6 support is still rather rare.

**Comment by Kenan-Mu** [comment]
Experiencing the same sort of thing on '.nl'. The code returns 

`{
  "domain_name": "domain.nl",
  "status": "active",
  "registrar": "TransIP Group",
  "registrar_address": "Vondellaan 47",
  "registrar_zip_code": "2332AA",
  "registrar_city": "LEIDEN",
  "registrar_country": "Netherlands",
  "dnssec": "yes",
  "name_servers": [
    "ns0.transip.net",
    "ns1.transip.nl",
    "ns2.transip.eu"
  ]
}
`

there is no date etc available.

**Comment by WKobes** [comment]
> Experiencing the same sort of thing on '.nl'. The code returns
> 
> `{ "domain_name": "domain.nl", "status": "active", "registrar": "TransIP Group", "registrar_address": "Vondellaan 47", "registrar_zip_code": "2332AA", "registrar_city": "LEIDEN", "registrar_country": "Netherlands", "dnssec": "yes", "name_servers": [ "ns0.transip.net", "ns1.transip.nl", "ns2.transip.eu" ] } `
> 
> there is no date etc available.

Hi @Kenan-Mu, this does not seem output from this package. I think this comes from the [richardpenman/whois](https://github.com/richardpenman/whois) package, so please raise this issue there!
