### ISSUE TITLE
WHOIS errors may lead to wrong domain being queried in secondary TLDs

### ISSUE THREAD

**Issue by WKobes** [DannyCork/python-whois#158]
**Describe the bug**
The following line strips a subdomain if an error/not found message is returned in the whois response
https://github.com/DannyCork/python-whois/blob/5e05a4aa82c1ae19b1029e6bbb4fdbc9a21a1974/whois/__init__.py#L83

In case of secondary TLDs, this may lead to returning the WHOIS response of the secondary TLD itself instead of an actual domain/not found. For example, time-out errors could easily trigger this bug.

Code should not strip last subdomain when an secondary TLD is used.

**Comment by maarten-boot** [comment]
has been fixed in latest pull request:

        # do we have a result and does it have a domain name
        if pd and pd["domain_name"][0]:
            return Domain(
                pd,
                verbose=verbose,
            )

        if len(d) > (len(tldLevel) + 1):
            d = d[1:]  # strip one element from the front and try again
            if verbose:
                print(f"try again with {d}, {len(d)}, {len(tldLevel)+1}", file=sys.stderr)
            continue

        # no result or no domain but we can not reduce any further so we have None
        return None
