### ISSUE TITLE
Wrong tag

### ISSUE THREAD

**Issue by fabaff** [DannyCork/python-whois#159]
**Describe the bug**
The latest release was tagged wrong. 9.9.10 instead of 0.9.10

This is a issue for NixOS and other distributions as the download URL for the source is often derived from the release numbering.

**To Reproduce**

Visit https://github.com/DannyCork/python-whois/releases/tag/9.9.10

**Comment by DannyCork** [comment]
Thanks for spotting this, I've yanked the 9.9.10

The whois release 0.9.9 released on 2021-04-13 has been yanked.
Yanked by: dannycork with a role: owner.
Reason: incorrect release tag
