### ISSUE TITLE
Make dateformats TLD-dependent to prevent ambiguous formats.

### ISSUE THREAD

**Issue by WKobes** [DannyCork/python-whois#166]
See discussion in #165

Parsing is now trial and error, which means that ambiguous formats may be parsed differently, even for the same TLD.

E.g. 13/04/2001 would only accept %d/%m/%Y, but 03/04/2001 might also match %m/%d/%Y.

Easiest solution would be to specify the allowed date formats per TLD. Even if a TLD would use multiple formats, the parsing should then succeed.

**Comment by sintemal** [comment]
I added a commit, which adds the option to specify a custom format for a TLD.

**Comment by WKobes** [comment]
Fixed in #165
