### ISSUE TITLE
API limit for whois

### ISSUE THREAD

**Issue by taru-svg** [DannyCork/python-whois#167]
Hey,
I am new to this repo, I wanted to know will this work if I wanted to get whois data for around 80K domains per day. I am using it for commercial purpose to help find malicious advertisements using the whois data. What is the api limit for python-whois? If not, then can someone please suggest alternative ways to get whois data for that many domains?

Thanks

**Comment by DannyCork** [comment]
It all depends on the policy of the whois server you are queuing, this repo doesn't influence that.

For bulk requests you will need to query an api like https://whois.whoisxmlapi.com

**Comment by lebonMIA** [comment]
Hi @DannyCork when the whois server actually limit requests, the command `whois.query(row[0])` returns a `None` value.
Is it safe to consider it means the request could not be performed ? or are there some legitimate cases where the whois would return nothing ?

**Comment by DannyCork** [comment]
Can you give me an example of what a whois server returns when it rejects a request due to rate limiting? I'm guessing a 403 Denied or a more correctly a 429 too many requests? Maybe the response is always same regardless of the whois server or maybe they are all implemented differently, I don't know tbh.

**Comment by lebonMIA** [comment]
for example the whois command on linux returns something like this :

```
%%
%% This is the AFNIC Whois server.
%%
%% complete date format : YYYY-MM-DDThh:mm:ssZ
%% short date format    : DD/MM
%% version              : FRNIC-2.5
%%
%% Rights restricted by copyright.
%% See https://www.afnic.fr/en/products-and-services/services/whois/whois-special-notice/
%%
%% Use '-h' option to obtain more information about this service.
%%
%% [########## REQUEST] >> -V Md5.5.10 ###########
%%
%% RL Net [########..] - RL IP [..........]
%%
%% Too many requests...
%%
```
I don't know exactly how the command speaks to the server but indeed it might be a "too many request" http error.
