### ISSUE TITLE
Python 3 run error 

### ISSUE THREAD

**Issue by xiqingongzi** [DannyCork/python-whois#17]
When I run 

``` python
import whois
domain = whois.query('google.com')
#print(domain.expiration_date)
print(domain.name)
```

i didn't get google.com but get the all context of whois .
Can you give me some example for Python3?

**Comment by alter** [comment]
python3 test_bug.py 
2020-09-14 00:00:00
google.com

cat test_bug.py 
import whois
domain = whois.query('google.com')
print(domain.expiration_date)
print(domain.name)

python3 -V          
Python 3.4.3+

python3.5 test_bug.py 
2020-09-14 00:00:00
google.com

python3.2 is also fine.

**Comment by DannyCork** [comment]
it works.
