### ISSUE TITLE
Version number in source / GitHub releases do not match PyPi

### ISSUE THREAD

**Issue by frenck** [DannyCork/python-whois#185]
## Describe the bug

The version number in the source doesn't match PyPi

https://github.com/DannyCork/python-whois/blob/f565af2eb22abcc615acc17550071f6418e32185/setup.py#L5

![image](https://user-images.githubusercontent.com/195327/150310832-8e7200f6-2f26-46ed-9186-e24e0c3ae62c.png)

Installing this package from the source is thus different.

The source downloaded from PyPi has a mismatching version/download URL

![image](https://user-images.githubusercontent.com/195327/150311241-b28c1fe9-58b2-495b-ae88-305c260a6ac2.png)

GitHub even has 0.9.14, which is not published on PyPi at all.

![image](https://user-images.githubusercontent.com/195327/150311510-abb9eab2-050c-450f-bb27-a7310a1f11e4.png)

## Expected behavior

Version across the different sources to match and be consistent.
Suggestion: Use a GitHub Action to publish on PyPi to ensure it is consistent.

## Additional context

I'm switching over Home Assistant to use this library, but since we pre-built wheels for quicker Docker image building and distribution, this becomes possibly problematic. As the pinned version doesn't match the one from source.

**Comment by DannyCork** [comment]
should be fixed now with 0.9.15

**Comment by frenck** [comment]
> should be fixed now with 0.9.15

Thanks! ❤️
