### ISSUE TITLE
Created and updated date 

### ISSUE THREAD

**Issue by elsheikh21** [DannyCork/python-whois#197]
Hello

I am using your package to fetch the domain's last updated date, expiry, and creation date, for some analysis
I just want to make sure that the dates used are related to the domain itself. not to the DNS server or Authorative server

```python
import whois


domain = whois.query('google.com')
print(domain.get("expiration_date"), domain.get("creation_date"), domain.get("last_updated"), sep='\n')

datetime.datetime(2020, 9, 14, 0, 0),
datetime.datetime(1997, 9, 15, 0, 0)
datetime.datetime(2011, 7, 20, 0, 0),


```

**Comment by maarten-boot** [comment]
as whois only has data for the (first level domain)
it is by definition of whois not related to and dns server 
and dns never returns dates anyway
see the output of the command line whois on any linux (and probabely windows/mac/...)

whois google.com
[Querying whois.verisign-grs.com]
[Redirected to whois.markmonitor.com]
[Querying whois.markmonitor.com]
[whois.markmonitor.com]
Domain Name: google.com
Registry Domain ID: 2138514_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.markmonitor.com
Updated Date: 2019-09-09T15:39:04+0000
Creation Date: 1997-09-15T07:00:00+0000
Registrar Registration Expiration Date: 2028-09-13T07:00:00+0000
Registrar: MarkMonitor, Inc.

**Comment by maarten-boot** [comment]
looks to me this can be closed
