### ISSUE TITLE
Error on: abroco.me

### ISSUE THREAD

**Issue by lolobosse** [DannyCork/python-whois#20]
I'm using your lib with dict and it fails with this log for `abroco.me`:

```
File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/whois/__init__.py", line 54, in query
    return Domain(pd) if pd['domain_name'][0] else None
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by DannyCork** [comment]
I get this

>>> import whois
>>> w = whois.query('abroco.me')
>>> print (w.__dict__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute '__dict__'

**Comment by DannyCork** [comment]
still an issue

**Comment by maarten-boot** [comment]
fixed by matching the string 

NOT FOUND (in lower case) to restult in a  None response if lines < 5

resulting in None

IMHO the issue can be closed
