### ISSUE TITLE
Error on date parsing/RegEx for .ua TLD

### ISSUE THREAD

**Issue by B-SPANO** [DannyCork/python-whois#201]
whois  zieit.edu.ua
% Request from 5.50.82.99
% This is the Ukrainian Whois query server #A.
% The Whois is subject to Terms of use
% See https://hostmaster.ua/services/
%
% IN THE PROCESS OF DELEGATION OF A DOMAIN NAME,
% THE REGISTRANT IS AN ENTITY WHO USES AND MANAGES A CERTAIN DOMAIN NAME,
% AND THE REGISTRAR IS A BUSINESS ENTITY THAT PROVIDES THE REGISTRANT
% WITH THE SERVICES NECESSARY FOR THE TECHNICAL MAINTENANCE OF THE REGISTRATION AND OPERATION OF THE DOMAIN NAME.
% FOR INFORMATION ABOUT THE REGISTRANT OF THE DOMAIN NAME, YOU SHOULD CONTACT THE REGISTRAR.

% % .UA whois
% Domain Record:
% =============
domain:     zieit.edu.ua
admin-c:    ZIEI-UANIC
tech-c:     LSIT-UANIC
tech-c:     SIN101-UANIC
status:     OK-UNTIL 20230425140101
nserver:    ns213.inhostedns.net
nserver:    ns113.inhostedns.com
nserver:    ns313.inhostedns.org
created:    0-UANIC 20190425140101
changed:    UARR168-UANIC 20220331171836
source:     UANIC

TRACEBACK:
Traceback (most recent call last):
  File "/home/brice/Workspace/project/WIP.py", line 23, in <module>
    who = whois.query('zieit.edu.ua')
  File "/home/brice/Workspace/project/venv/lib/python3.9/site-packages/whois/__init__.py", line 113, in query
    return Domain(pd)
  File "/home/brice/Workspace/project/venv/lib/python3.9/site-packages/whois/_3_adjust.py", line 18, in __init__
    self.creation_date = str_to_date(data['creation_date'][0], self.tld.lower())
  File "/home/brice/Workspace/project/venv/lib/python3.9/site-packages/whois/_3_adjust.py", line 136, in str_to_date
    raise UnknownDateFormat("Unknown date format: '%s'" % text)
whois.exceptions.UnknownDateFormat: Unknown date format: '0-uanic 20190425140101'

Process finished with exit code 1

**Comment by B-SPANO** [comment]
only affect UANIC records, not UAEPP records.
(miss clic :'( )

**Comment by maarten-boot** [comment]
added it to the test.py for further fixing

**Comment by maarten-boot** [comment]
fixed in the latest pull request
