### ISSUE TITLE
Improve response for Private Registry (like .ch)

### ISSUE THREAD

**Issue by B-SPANO** [DannyCork/python-whois#202]
Some registry like Switch (case of .ch and .li TLDs) are not allowed queries from whois and use webpage and captcha to answer a very light amount of information (registrar, name server, DNSSEC and first date of registration).
Can be interesting to add an exception PrivateRegistry and catch response string (who contains url for webpage).
Lot of registries have censored (private) information and more will.

**Comment by maarten-boot** [comment]
can be closed
