### ISSUE TITLE
Error on: addersp.it

### ISSUE THREAD

**Issue by lolobosse** [DannyCork/python-whois#21]
Hey,

Other error on `it` tld: I got this log:

```
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/whois/__init__.py", line 50, in query
    pd = do_parse(do_query(d, force, cache_file, slow_down, ignore_returncode), tld)
  File "/Library/Python/2.7/site-packages/whois/_2_parse.py", line 36, in do_parse
    raise Exception(whois_str)
Exception: Domain:             addersp.it
Status:             AVAILABLE
```

**Comment by DannyCork** [comment]
`>>> domain = whois.query('google.it')
>>> print(domain.__dict__)
{'name': 'it', 'registrar': '', 'creation_date': datetime.datetime(1987, 12, 23, 0, 0), 'expiration_date': datetime.datetime(2020, 4, 21, 0, 0), 'last_updated': datetime.datetime(2019, 5, 7, 1, 4, 50), 'name_servers': set()}`

can't recreate

**Comment by DannyCork** [comment]
>>> print (domain.__dict__)
{'name': 'addersp.it', 'registrar': '', 'registrant_country': '', 'creation_date': None, 'expiration_date': None, 'last_updated': None, 'status': 'AVAILABLE', 'statuses': ['AVAILABLE'], 'dnssec': False, 'name_servers': set()}
