### ISSUE TITLE
unable to use the module in Serverless

### ISSUE THREAD

**Issue by devikarthikd** [DannyCork/python-whois#218]
The following is raising while trying to work through Serverless gitlab yml

[ERROR]	2022-09-21T11:00:27.151Z	71ab2ee9-53ca-4212-b96a-57319380c387	Exception occured while looking for domain info using python whois ,Exception : [Errno 2] No such file or directory: 'whois'
Traceback (most recent call last):
  File "/var/task/domain_lookup_module.py", line 38, in whois_lookup
    result = whois.query(domain)
  File "/var/task/whois/__init__.py", line 206, in query
    q = do_query(
  File "/var/task/whois/_1_query.py", line 62, in do_query
    _do_whois_query(
  File "/var/task/whois/_1_query.py", line 119, in _do_whois_query
    p = subprocess.Popen(
  File "/var/lang/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/var/lang/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'whois'

**Comment by maarten-boot** [comment]
yes that is perfectly normal and expected
if your CI test server-less thingy has no whois command then the code
cannot be tested in its current form

Note the module just parses the normal output of the Windows or Linux
resident whois command
so the module depends for its functioning on the existence of the whois
command in any environment (so also during test)

**Comment by maarten-boot** [comment]
i expect this issue can be closed

**Comment by devikarthikd** [comment]
Thank you for response, so I did apt install Whois while testing its
deployed but it is showing same error when working as stepfunction

**Comment by maarten-boot** [comment]
Sorry but i belong to the oldies, what is a step function and in what place
and context does it execute ?
