### ISSUE TITLE
blank for some domains

### ISSUE THREAD

**Issue by edel** [DannyCork/python-whois#219]
i get blank expiration_data for domain like `kpvalidate.me`. probably because the last line (with string Expiration Date:) has no value.
```(adm) edel@palatug ~ 
$ python
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import whois
>>> d=whois.query('google.com')
>>> d.expiration_date
datetime.datetime(2028, 9, 14, 4, 0)
>>> d=whois.query('kpvalidate.me')
>>> d.expiration_date
>>> 
(adm) edel@palatug ~ 
$ whois kpvalidate.me | grep -i expir
Registry Expiry Date: 2023-01-07T15:35:57Z
Registrar Registration Expiration Date:
(adm) edel@palatug ~ 
$ 
```
thank you for the library.

**Comment by maarten-boot** [comment]
yes this is normal behavior,
as the output from whois has no date so the python library has no date as
there is nothing to parse
it is not mandatory to actually have a expiry date in the whois output as
every registrar has its own internal policies

**Comment by maarten-boot** [comment]
i expect this issue can be closed
