### ISSUE TITLE
function do_parse output a FailedParsingWhoisOutput error when trying to parse a small WHOIS

### ISSUE THREAD

**Issue by friscofrance** [DannyCork/python-whois#221]
## Describe the bug
function **do_parse** output a **FailedParsingWhoisOutput** error when trying to parse a small **WHOIS**

## Screenshots
domain used :
>globalgroup.co.uk

whois obtained :
>Expiry date: 17-Oct-2023\nLast updated: 14-Jun-2022\nRegistered on: 17-Oct-2017\nns55.domaincontrol.com\nns56.domaincontrol.com

my code
![image](https://user-images.githubusercontent.com/31140704/192790202-af627e66-cd8b-44af-b33c-ac4858856dbb.png)
![image](https://user-images.githubusercontent.com/31140704/192791526-7da6703e-b0c8-4023-b34a-510b4e8c2a05.png)

my output
![image](https://user-images.githubusercontent.com/31140704/192789929-3d90d7be-08cc-4786-bbd4-a0f543fb34c6.png)

## Additional context
For a domain analysis project, i'm in the need of parsing a lot of whois. I found this library very usefull but during my test on some of my data i've found this error. 
I don't think it's intended to not at parse small whois like those, correct me if i'm wrong. Otherwise script work perfectly fine with bigger one and output a usesable dict.

**Comment by maarten-boot** [comment]
when using the latest pip version
and using the module the normal way 

{code}
import whois

domain = whois.query("globalgroup.co.uk")
print(domain.__dict__)
{code}

no error occurs:

{code}
{'name': '', 'tld': 'uk', 'registrar': '', 'registrant_country': '', 'creation_date': datetime.datetime(2017, 10, 17, 0, 0), 'expiration_date': datetime.datetime(2023, 10, 17, 0, 0), 'last_updated': datetime.datetime(2022, 9, 13, 0, 0), 'status': '', 'statuses': [''], 'dnssec': False, 'name_servers': ['ns55.domaincontrol.com'], 'registrant': ''}
{code}

however i see that the name_servers output is not complete in this case

{code}
    Domain name:
        globalgroup.co.uk

    Data validation:
        Nominet was able to match the registrant's name and address against a 3rd party data source on 16-Jun-2021

    Registrar:
        GoDaddy.com, LLC. [Tag = GODADDY]
        URL: http://uk.godaddy.com

    Relevant dates:
        Registered on: 17-Oct-2017
        Expiry date:  17-Oct-2023
        Last updated:  13-Sep-2022

    Registration status:
        Registered until expiry date.

    Name servers:
        ns55.domaincontrol.com
        ns56.domaincontrol.com

    WHOIS lookup made at 10:54:59 01-Oct-2022
{code}

**Comment by maarten-boot** [comment]
fixed in #231

**Comment by maarten-boot** [comment]
i expect this issue can be closed
