### ISSUE TITLE
How to get the content downloaded from whois server

### ISSUE THREAD

**Issue by baigreen** [DannyCork/python-whois#235]
like

>>> w.text  # the content downloaded from whois server
u'\nDomain Name: EXAMPLE.COM
Registry Domain ID: 2336799_DOMAIN_COM-VRSN
...'

**Comment by maarten-boot** [comment]
yes i have been thinking about how to add the raw output of the whois command to the output of whois.query.
it is not 100% possible but in most cases it should be possible to also add the raw output , i will implement that in the next change

**Comment by maarten-boot** [comment]
should become possible after #237 has been merged, the text field can then be requested with the boolean flag: include_raw_whois_text set to True

**Comment by baigreen** [comment]
Thanks for the work.
