### ISSUE TITLE
Discussion: tld outside of package version

### ISSUE THREAD

**Issue by maarten-boot** [DannyCork/python-whois#242]
Currently supporting additional tld requires a new version of the package.

I have been wondering if the supported tld's could be disconnected from the package.
In terms of code is is not very difficult but there are naturally other factors beside the code changes.

if we would move the current data in tld_regexpr.py to a json or yaml file and we allow the whois interface to point to a file outside of the package while providing a default in case no file is specified, we could disconnect the adding of tld's from the package version.

A validator for the file format would be advisable in this case, and i can foresee issues with air-gapped environments or environments that frown on downloading data from the internet so the file should be part of the package also but additions or changes could be added and merged at runtime. 
This would allow fast changes for those who only use the package by just adding new domains via a outside file that will be merged in the tld and regexp pool.

let me hear your thoughts on this.

Maarten

**Comment by maarten-boot** [comment]
as a precursor i rewrote the tld_regexpr to use a dict
this gets rid of all mappings using _ instead of . and we dont need to hide python keywords
the _0_init_tld will do the loading on import to setup the dict of regexpr 

https://github.com/maarten-boot/python-whois/tree/experiment-tld-dict

**Comment by maarten-boot** [comment]
a  example override and defining previously unsupported domain are now in the experimental branch at my repo

https://github.com/maarten-boot/python-whois/blob/experiment-tld-dict/testExtend.py

**Comment by maarten-boot** [comment]
is this a acceptable move forward ?
shall i make a implementaton for it ?

**Comment by DannyCork** [comment]
yes , lets do it :)

**Comment by maarten-boot** [comment]
in pull/258

**Comment by maarten-boot** [comment]
can be closed
