### ISSUE TITLE
Wrong nameserver values

### ISSUE THREAD

**Issue by Aeonian9** [DannyCork/python-whois#249]
## Describe the bug
Domain logist.it nameservers return wrong values.

## To Reproduce
```
>>> whois.query('logist.it').name_servers
['e', 'ns1.nss.ee', 'ns2.nss']
```

## Expected behavior
Nameservers should have values "ns1.nss.ee" and "ns2.nss.ee".

## Version:
Whois version 0.9.18

**Comment by maarten-boot** [comment]
fixed in https://github.com/DannyCork/python-whois/pull/250
