### ISSUE TITLE
'str' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by Sh0gunBR** [DannyCork/python-whois#252]
i was coding my whois automation, and this error appeared:
'str' object has no attribute '__dict__'
and the code is the same as readme, but i modified them

**Comment by maarten-boot** [comment]
if you could provide a example and the string you get returned that would be helpful

**Comment by maarten-boot** [comment]
i see that in your hellcat repo requirements.txt you include 2 different whois packages, that is asking for trouble, only one package should be installed at a time
```
termcolor
python-whois
whois < remove this one if you want to use python-whois (this repo)
pyfiglet
```

**Comment by maarten-boot** [comment]
i expect we can close this issue
