### ISSUE TITLE
Add .kz

### ISSUE THREAD

**Issue by constantinekg** [DannyCork/python-whois#26]
There is no .kz zone (whois.nic.kz)

**Comment by Pherang** [comment]
Added some required keys in pull request "Added required keys for kz domain #142"
Hope that helps!

**Comment by DannyCork** [comment]
{'DNSSEC': False, 'domain_name': ['test.kz'], 'registrar': ['ICPS'], 'registrant_country': ['KZ'], 'expiration_date': [''], 'creation_date': ['2008-01-28 10:06:16 (GMT+0:00)'], 'updated_date': ['2012-08-07 13:10:03 (GMT+0:00)'], 'name_servers': ['ns1.skilltex.kz', 'ns2.skilltex.kz'], 'status': ['clientTransferProhibited - ']}
