### ISSUE TITLE
IP range lookup supported

### ISSUE THREAD

**Issue by llang629** [DannyCork/python-whois#268]
Not clear from reading the docs and code whether whois lookup of an IP address (or address range) is supported.

For example, from a Unix command line:
whois 102.23.224.0/19
returns whois information about the ISP allocated that block of IP addresses.

Is something like that possible using this wrapper?

Thank you!

**Comment by maarten-boot** [comment]
Not supported, and no plans to support.
Best look at ipwhois.

**Comment by maarten-boot** [comment]
i expect that this issue can be closed

**Comment by llang629** [comment]
Yes, thanks for the quick reply and suggestion.
