### ISSUE TITLE
Module doesn't work in python 3.5.3

### ISSUE THREAD

**Issue by MBWlodarczyk** [DannyCork/python-whois#275]
There is an error when trying to run module under python 3.5.3.

 import whois
  File "---/python3.5/site-packages/whois/__init__.py", line 98
    print(f"filterTldToSupportedPattern returns tld: {tld}", file=sys.stderr)

This issue is caused by using the new format string intruduced in python 3.6.

**Comment by maarten-boot** [comment]
i suggest strongly you upgrade to at least 3.6

https://www.python.org/downloads/release/python-3510/
Python 3.5.10

Python 3.5 has reached end-of-life. Python 3.5.10 is the final release of
3.5.

Python 3.5.10 was released on September 5th, 2020.

Python 3.5.10 is the final release in the Python 3.5 series. As of this
release, the 3.5 branch has been retired, no further changes to 3.5 will be
accepted, and no new releases will be made. This is standard Python policy;
Python releases get five years of support and are then retired.

If you're still using Python 3.5, you should consider upgrading to the current
version. <https://www.python.org/downloads/> Newer versions of Python have
many new features, performance improvements, and bug fixes, which should
all serve to enhance your Python programming experience.

**Comment by MBWlodarczyk** [comment]
Thanks for quick reply, i'm closing the issue.

**Comment by maarten-boot** [comment]
;-)
