### ISSUE TITLE
Code in documentation didn't work

### ISSUE THREAD

**Issue by Willmizzle** [DannyCork/python-whois#301]
```
import whois
domain = whois.query('google.com')
print(domain.___dict___)
```
gives

_AttributeError: module 'whois' has no attribute 'query'_

**Comment by maarten-boot** [comment]
looks like you are mixing 2 whois repositories, this has append before.

the confusion arises from the differences between the pip install and the GitHub names
there are 2 whois modules in pip:
1. pip: https://pypi.org/project/python-whois/ is in github: https://github.com/richardpenman/whois 
2. pip: https://pypi.org/project/whois/ is in               github: https://github.com/DannyCork/python-whois/ 

we are: 2             we have whois.query()
you installed 1   they use whois.whois()

**Comment by maarten-boot** [comment]
i expect this can be closed ?-
