### ISSUE TITLE
I think a try-except would be better when trying more details.

### ISSUE THREAD

**Issue by baigreen** [DannyCork/python-whois#304]
```
>>> whois.query("web3gpt.com")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/code/whois/python_whois/whois/__init__.py", line 279, in query
    whois_str = do_query(
  File "/home/ubuntu/code/whois/python_whois/whois/_1_query.py", line 71, in do_query
    _do_whois_query(
  File "/home/ubuntu/code/whois/python_whois/whois/_1_query.py", line 194, in _do_whois_query
    raise WhoisCommandFailed(r)
whois.exceptions.WhoisCommandFailed: fgets: Connection reset by peer
   Domain Name: WEB3GPT.COM
```

**Comment by maarten-boot** [comment]
we actually use a try: block

https://github.com/DannyCork/python-whois/blob/master/whois/_1_query.py#L182

**Comment by maarten-boot** [comment]
what would you prefer in this case, a simple None response without any cause 
or should we add something like the whois.query() returns None 
and a additional call like last_status could return: 

FailedParsingWhoisOutput (in my case) or WhoisCommandFailed (in your case)

**Comment by baigreen** [comment]
I am not sure.
In my opinion, the service for getting basic information should be stable. 

For .com, I think the first step is
`whois -h whois.verisign-grs.com web3gpt.com`
 to get the basic information, and the second step is 
` whois -h whois.22.cn web3gpt.com` 
 Even if the second step fails, it should return the main information already obtained in the first step.

**Comment by maarten-boot** [comment]
Well that happens all inside the cli whois command and is different on mac then on linux.
on Mac the cli whois has a tendency to show all steps of the redirect, 
on Linux the cli whois only shows the final redirect result.

I have no influence on the behavior of how the cli whois does its work, 
all we can do is ignore the error code of whois and do our best to parse the result if there is any, 
for the ignore error code we already have a option on whois.query

example with your command above:

```whois -h whois.verisign-grs.com web3gpt.com
[Querying whois.verisign-grs.com]
[Redirected to whois.22.cn]
[Querying whois.22.cn]
[whois.22.cn]
```

```
 whois -h whois.22.cn web3gpt.com
[Querying whois.22.cn]
[whois.22.cn]
```

**Comment by baigreen** [comment]
#306 add a simple way to ignore the error.
Will close it.
