### ISSUE TITLE
Whois on IP

### ISSUE THREAD

**Issue by s23hck** [DannyCork/python-whois#305]
Hi, 
Thanks for this tool !
Does python-whois can extract information like organization name from an IP ?

**Comment by maarten-boot** [comment]
No we do not support ip based lookup
There is another package available for ip lookups

**Comment by maarten-boot** [comment]
For ip lokups you ciuld use
https://pypi.org/project/ipwhois

**Comment by s23hck** [comment]
Ok ! Thanks for your answer and for ipwhois :)
Have a nice day !
cheers
