### ISSUE TITLE
status whois on pipy

### ISSUE THREAD

**Issue by maarten-boot** [DannyCork/python-whois#308]
Subject: status whois on pipy
I noted you have not released a new version for some time,
hope all is ok with you.
 
I have created a pipy account (mboot) 
so if you want to add me as co-maintaner on pipy i can (take over/assist in) releasing.

alternatively if you prefer, i can create me own package on pipy, that is also fine with me.
i would then create a new name DomainWhois (like there is IpWhois on pipy)
this would also reduce the mistakes people make when mixing the whois and the python-whois packages 

happy Easter,

maarten

**Comment by mboot-github** [comment]
FYI:

a new pypi library exists now at: https://pypi.org/project/whoisdomain/

it is a cleaned up copy of this repo, i switched to versioning from 1.x.y where x is YYYYMMDD and y starts from 1 in case we need more then one pypi upload per day

the whois directory is renamed to whoisdomain and the package is released as whoisdomain , currently the actual code is unchanged
 
code is maintained at: https://github.com/mboot-github/WhoisDomain

when importing as :
```
import whoisdomain as whois
```
the rest of your code can stay the same
