### ISSUE TITLE
Check if domain is available, not available or in redemption period

### ISSUE THREAD

**Issue by Willmizzle** [DannyCork/python-whois#313]
I am trying to write a function that checks whether a domain is available to register, not available to register or in the redemption period, and is as accurate as possible. Here is my code:

```
import whois
import requests
  
  def is_redirect(input_domain):
      try:
          response = requests.head("http://" + input_domain, timeout=10)
  
          if response.status_code in [301, 302]:
              return True
          else:
              return False
      except Exception as e:
          print(f"Error checking domain {input_domain}: {e}")
          return False
  
  def is_domain_expired(input_domain):
      if is_redirect(input_domain):
          return "Domain is a redirect and not available to register."
      try:
          domain = whois.whois(input_domain)
          
          if "redemptionPeriod" in domain.status:
              print(f"{input_domain} is in redemption period.")
          elif domain.status is None:
              print(f"{input_domain} is available for registration.")
          else:
              print(f"{input_domain} is not available for registration.")
      except whois.parser.PywhoisError as e:
          if "No match for" in str(e):
              print(f"{input_domain} is available for registration.")
          else:
              print(f"Error checking domain {input_domain}: {str(e)}")
      except Exception as e:
          print(f"Error: {str(e)}")
  
  while True:
      domain = input("domain to check: ")
      is_domain_expired(domain)

```

I entered a domain which I know is in the redemption period, but it prints that the domain is available for registration. How do I code this properly?

**Comment by maarten-boot** [comment]
Will have a look. What domain did you try this with ?

**Comment by maarten-boot** [comment]
Note that you are currently usung whois.whois()
This library uses whois.query()
https://github.com/richardpenman/whois is the repositiry for that whois
library on github.

**Comment by Willmizzle** [comment]
> Will have a look. What domain did you try this with ?

tujobs.com

**Comment by Willmizzle** [comment]
> Note that you are currently usung whois.whois() This library uses whois.query() https://github.com/richardpenman/whois is the repositiry for that whois library on github.

Wait... am I to understand that for the python-whois repository, you would install it with pip install whois, and for the whois repository, you install it with pip install python-whois?

**Comment by Willmizzle** [comment]
By the way,  print(domain.__dict__) as seen in the documentation gives me: AttributeError: 'str' object has no attribute '__dict__'. Did you mean: '__dir__'?

**Comment by maarten-boot** [comment]
Yes exactly that.
the name confusion is a great source of issues.
That is why i started whoisdomain as can be seen in the readme.

**Comment by maarten-boot** [comment]
Yes that is due to being on the wrong repo for instructions on your version
of whois for python
 we use whois.query where geting the results as a dict are supported.

**Comment by maarten-boot** [comment]
When in doubt always compare with the raw output of the cli whois command,
 in the case of your domajn i get no useful info after some redirects, ymmv
as i am on fedora37.

**Comment by maarten-boot** [comment]
i expect we can close this issue ?
