### ISSUE TITLE
cmd parameter not being passed to do_query()

### ISSUE THREAD

**Issue by SliceOfLife** [DannyCork/python-whois#315]
## Describe the bug
When we call whois.query() we can set the "whois" command via the cmd parameter. But this value is not passed to do_query() in the following flow. See https://github.com/DannyCork/python-whois/blob/master/whois/__init__.py#L326

## To Reproduce
```
        domain = whois.query(
            domain,
            force=True,
            cmd="proxychains -q whois"
        )
```

**Comment by maarten-boot** [comment]
- the command was passed but the string was not split into a list and merged with the other options
- when you add the verbose flag you can see that the command is now properly forwarded complete

**Comment by maarten-boot** [comment]
can close this issue ?
