### ISSUE TITLE
Add a redis cache

### ISSUE THREAD

**Issue by baderdean** [DannyCork/python-whois#327]
I'm using this library with a redis cache in front. I just saw that you did implement also a file cache.
Could you implement an async redis cache in addition to file cache please?
https://github.com/DannyCork/python-whois/blob/58a508398d11dd68d74b928cd8a974e6a0849701/whois/_1_query.py#L197

**Comment by maarten-boot** [comment]
this will need some thinking to make sure it only is needed if redis is actually installed and requested to be used for cache

**Comment by maarten-boot** [comment]
note new development is done in: https://github.com/mboot-github/WhoisDomain
and then synced back to this repo, feel free to make the request there also

**Comment by maarten-boot** [comment]
added in https://github.com/DannyCork/python-whois/commit/f6c518827ed23850a519352d5428b3bf967f72a9
