### ISSUE TITLE
AttributeError: module 'whois' has no attribute 'query'

### ISSUE THREAD

**Issue by rainbowhat** [DannyCork/python-whois#38]
AttributeError: module 'whois' has no attribute 'query'

**Comment by dynamicdeploy** [comment]
I got this too. works on command line but from a code file gives this problem

**Comment by DannyCork** [comment]
@rainbowhat @dynamicdeploy  can you give more details please as I can't recreate this issue.

**Comment by huberb** [comment]
i had the same problem, turns out it's a python thing.

just don't call your python file 'whois.py', since the line 'import whois' will import itself then.
i fixed this problem by renaming the file to something else than whois.py

you can recreate this by creating a file called 'whois.py' and import whois. i don't think there is anything to fix

**Comment by DannyCork** [comment]
closing as not an issue as @huberb pointed out

Thanks for the comments @huberb

**Comment by xtendtech** [comment]
I had same issue because the program had same name whois.py...So dont use same name as the library

**Comment by BenChueh** [comment]
> i had the same problem, turns out it's a python thing.
> 
> just don't call your python file 'whois.py', since the line 'import whois' will import itself then. i fixed this problem by renaming the file to something else than whois.py
> 
> you can recreate this by creating a file called 'whois.py' and import whois. i don't think there is anything to fix

well i named my directory "DNSLookUp" and the file is "main.py" the bug still goes off

**Comment by maarten-boot** [comment]
just to confirm: what library of whois are you using ?
there are 2 very similar packages on pip/pypi

1) https://pypi.org/project/python-whois/ (latest version 0.8.0 )
2) https://pypi.org/project/whois/ (latest version 0.9.18 )

for 1 you import whois and use whois.whois
for 2 you import whois and use whois.query

they normally should not be installed at the same time unless you need trouble in paradise ;-)
