### ISSUE TITLE
extend support for .pl domains

### ISSUE THREAD

**Issue by zagi** [DannyCork/python-whois#41]
**Extend support**
Extend regex for .pl to support domain other than active states.

**whois** for active domains returns the expiration date under "renewal date" line however there are other states for domains and now the expiration date for them is returned None, but it is actually returned from whois but under "expiration date" line.

best,
mike

**Comment by zagi** [comment]
attaching pull request:
#42

**Comment by DannyCork** [comment]
fixed by https://github.com/DannyCork/python-whois/pull/108
