### ISSUE TITLE
Generic Exceptions

### ISSUE THREAD

**Issue by stylesuxx** [DannyCork/python-whois#44]
There are a couple of places where this library is raising exceptions that are just generic exceptions, this makes it very hard for me to see what actually happened.

I am willing to submit a PR for with the following custom exceptions:
* [x] **UnknownTld** instead of **Exception**
* [x] **UnknownDateFormat** instead of **ValueError**
* [x]  **WhoisCommandFailed** insted of **Exception**
* [x] **FailedParsingWhoisOutput** instead of **Exception**

@DannyCork is this something you would be interested in merging?

**Comment by DannyCork** [comment]
HI Styleuxx, 
Thanks for your kind offer. Your pr will be most welcome.
