### ISSUE TITLE
Local variable 'tz' is referenced before assignment

### ISSUE THREAD

**Issue by Nilsbijlsma** [DannyCork/python-whois#53]
I installed the library via pip, I also installed Linux Whois via apt-get.

I have the following code:
```
import whois
domain = whois.query('google.com')
```

However, the following error pops up: Local variable 'tz' is referenced before assignment.
This comes up from the _3_adjust.py file:

```
def str_to_date_py2(s):
    tmp = re.findall('\+([0-9]{2})00', s)
    if tmp:
        tz = int(tmp[0])
    else:
        z = 0

    for format in DATE_FORMATS:
        try:
            return datetime.datetime.strptime(s, format) + datetime.timedelta(hours=tz)
        except ValueError:
            pass

raise UnknownDateFormat("Unknown date format: '%s'" % s)
```

It seems that 'tz' is only assigned if 'tmp' exists. In other cases 'z' is assigned 0. I assume this needs to be tz instead of z?

**Comment by DannyCork** [comment]
Well spotted. This is an issue with python 2.x.
As you pointed out, I have added a fix for this https://github.com/DannyCork/python-whois/commit/11fb18d0759baf3a7600c68370a1c91b5b4769fa

Please pull master and verify the fix.

**Comment by Nilsbijlsma** [comment]
Ah yes, I should've added that I was using Python 2.7.13
However, when running the same code as before I'm now getting the following traceback:

`Python 2.7.13 (default, Nov 23 2017, 15:37:09) 
[GCC 6.3.0 20170406] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import whois
>>> domain = whois.query('google.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/whois/__init__.py", line 61, in query
    pd = do_parse(do_query(d, force, cache_file, slow_down, ignore_returncode), tld)
  File "/usr/local/lib/python2.7/dist-packages/whois/_1_query.py", line 46, in do_query
    _do_whois_query(dl, ignore_returncode),
  File "/usr/local/lib/python2.7/dist-packages/whois/_1_query.py", line 60, in _do_whois_query
    p = subprocess.Popen(['whois', '.'.join(dl)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
`
I went through the listed files and they all seem to be present in those specific directories.

**Comment by DannyCork** [comment]
Python 2 not supported.
