### ISSUE TITLE
object has no attribute 'query'

### ISSUE THREAD

**Issue by Finch4** [DannyCork/python-whois#55]
I already know that this problem has already been solved, but the solution for me was not that.
-my .py file name isn't whois.py
-whois version 0.8
-installed with `pip3 install whois`

Code:
`
target = ('google.com')`
`n = whois.query(target)`
`print(n) `

**Comment by DannyCork** [comment]
thanks for raising the issue report.

I used the following code using python 3.6 :
```
import whois

target = ('google.com')
n = whois.query(target)
print(n.__dict__)
```

and got 
```
$ p x.py 
{'name': 'google.com', 'registrar': 'MarkMonitor Inc.', 'creation_date': datetime.datetime(1997, 9, 15, 4, 0), 'expiration_date': datetime.datetime(2020, 9, 14, 4, 0), 'last_updated': None, 'name_servers': {'ns2.google.com', 'ns3.google.com', 'ns1.google.com', 'ns4.google.com'}}
```

What version of python are you using?

**Comment by DannyCork** [comment]
fixed in https://pypi.org/project/whois/0.9.2/

Please do a $ pip install --upgrade whois 
and report back.
Thanks.

**Comment by Arinze1020** [comment]
Haven the same issue on -version 0.9.3 
saying 'whois' has no attribute 'query'

**Comment by MariusMez** [comment]
Maybe you have an other python package with same import name. It's the case with the module python-whois which use the package name 'whois' too.

Try `pip uninstall python-whois` to check that

**Comment by nicksamuel** [comment]
Can confirm uninstalling python-whois did the trick for me, seems there was a conflict. Thanks!

**Comment by IgorSonehara** [comment]
Had the same problem, for some reason the name of file can't be whois.py
