### ISSUE TITLE
add .ir tld

### ISSUE THREAD

**Issue by saeidshirazi97** [DannyCork/python-whois#56]
hi please add .ir domain

**Comment by nickmasster** [comment]
Looks liked fixed in merged PR #93.

**Comment by fhightower** [comment]
@DannyCork : I believe this issue can be closed (see https://github.com/DannyCork/python-whois/pull/93).

**Comment by DannyCork** [comment]
🇮🇷 🇮🇷 🇮🇷 🇮🇷 🇮🇷 🇮🇷 🇮🇷 🇮🇷
