### ISSUE TITLE
Not available from Django

### ISSUE THREAD

**Issue by tkhr2019** [DannyCork/python-whois#59]
Hello.

I want to use whois.query from Django.
But it didn't work.

From my python console on my windows10 and ubuntu18.4
The following code worked.

$ python
> import whois
> domain = whois.query('google.com')
> print(domain.__dict__)

But when you call whois.query from Django,
The domain variable is None.

Looking at the source code, you can see that None is returned in the following places.

> return Domain(pd) if pd['domain_name'][0] else None

Please let me know how you can use it in Django.

Thanks.

**Comment by DannyCork** [comment]
should be __dict__
ie: print(domain.__dict__)
