### ISSUE TITLE
.pl domain always return "request limit exceeded"

### ISSUE THREAD

**Issue by azzamsa** [DannyCork/python-whois#60]
**Describe the bug**
we always have "request limit exceeded". when doing `whois` for .pl domains. The problem is not the code. but the domain itself.

I need to open this issue, to discuss, on how to handle this problem. Should we wait for the domain to be corrected. Or should we handle "request limit exceeded", in our codebase ?

**To Reproduce**
1. run the test
2. or run `$ whois google.pl` (yes, the error is not from our codebase)

**Comment by DannyCork** [comment]
I did a whois google.pl
`$ whois google.pl
 
DOMAIN NAME:           google.pl 
registrant type:       organization 
nameservers:           ns1.google.com.  
                       ns2.google.com.  
                       ns3.google.com.  
                       ns4.google.com.  
created:               2002.09.19 13:00:00 
last modified:         2019.08.17 11:36:41 
renewal date:          2020.09.18 14:00:00 
 
option created:        2017.10.14 09:30:46 
option expiration date:       2020.10.14 09:30:46 
 
dnssec:                Unsigned 
 
 
REGISTRAR: 
Markmonitor, Inc.
3540 East Longwing Lane, Suite 300
Meridian, Idaho 83646
United States
+1.2083895740
ccops@markmonitor.com 
 
WHOIS database responses and Registrant data available at: https://dns.pl/en/whois 
 
WHOIS displays data with a delay not exceeding 15 minutes in relation to the .pl Registry system 
`

Closing as this is a local problem whereby you are exceeding the request limit.
