### ISSUE TITLE
Can't get nameservers on newest revision

### ISSUE THREAD

**Issue by azzamsa** [DannyCork/python-whois#65]
**Describe the bug**
The newest revision can't get the `name_servers`. I have my old build and still running well in remote vm

**To Reproduce**
1. create new virtualenv
2. `$ pip install git+https://github.com/DannyCork/python-whois`
3. get the domain data

```python
$ python
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import whois
>>> domain = whois.query('google.com')
>>> print(domain.__dict__)
{'name': 'google.com', 'registrar': 'MarkMonitor Inc.', 'creation_date': datetime.datetime(1997, 9, 15, 4, 0), 'expiration_date': datetime.datetime(2020, 9, 14, 4, 0), 'last_updated': None, 'name_servers': set()}
>>>
```

**Expected behavior**
the `name_servers` shouldn't be None

**Additional context**
```python
$ pip freeze --local
pkg-resources==0.0.0
whois==0.9.3


$ python --version
Python 3.7.3

```

**Comment by unggulzmalqp** [comment]
The indentation altered on the newest version. Giving the right indentation this block of code fixes the problem

https://github.com/unggulzmalqp/python-whois/commit/5a7a3f29e3a7f70667ebe296a2207fa33f7aeb66
