### ISSUE TITLE
No support for .edu TLD?

### ISSUE THREAD

**Issue by netops2devops** [DannyCork/python-whois#66]
I just tried querying a domain with .edu and got the following error: 

Traceback (most recent call last):
  File "./func_args.py", line 14, in <module>
    domain = whois.query('ncsa.illinois.edu')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/whois/__init__.py", line 58, in query
    raise UnknownTld('Unknown TLD: %s\n(all known TLD: %s)' % (tld, list(TLD_RE.keys())))
whois.exceptions.UnknownTld: Unknown TLD: edu
(all known TLD: ['com', 'at', 'uk', 'pl', 'be', 'biz', 'br', 'ca', 'cc', 'co', 'jp', 'co_jp', 'cz', 'de', 'eu', 'fr', 'id', 'info', 'io', 'it', 'ru', 'lv', 'me', 'mobi', 'mx', 'name', 'net', 'nyc', 'nz', 'online', 'org', 'press', 'pw', 'store', 'rest', 'ru_rf', 'security', 'sh', 'site', 'space', 'tech', 'tel', 'theatre', 'tickets', 'tv', 'us', 'uz', 'video', 'website', 'wiki', 'xyz'])

Can I please request support for .edu TLD to be added to the API?

Thanks!

-Kapil.

**Comment by fhightower** [comment]
@DannyCork : I think this issue can be closed (based on https://github.com/DannyCork/python-whois/pull/76).
