### ISSUE TITLE
TLD .de not working

### ISSUE THREAD

**Issue by peet47** [DannyCork/python-whois#72]
query from any domain from .de is not working

Python 3.7.4 (default, Sep  7 2019, 18:27:02) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import whois
>>> data = whois.query("google.com")
>>> print(data.__dict__)
{'name': 'google.com', 'registrar': 'MarkMonitor Inc.', 'creation_date': datetime.datetime(1997, 9, 15, 4, 0), 'expiration_date': datetime.datetime(2028, 9, 14, 4, 0), 'last_updated': None, 'name_servers': set()}
>>> data = whois.query("spiegel.de")
>>> print(data.__dict__)
{'name': 'de', 'registrar': '', 'creation_date': None, 'expiration_date': None, 'last_updated': datetime.datetime(2019, 10, 29, 0, 0), 'name_servers': {'l.de.net', 's.de.net', 'a.nic.de', 'n.de.net', 'z.nic.de', 'f.nic.de'}}

▶ whois spiegel.de
% IANA WHOIS server
% for more information on IANA, visit http://www.iana.org
% This query returned 1 object

refer:        whois.denic.de

domain:       DE

organisation: DENIC eG
address:      Kaiserstrasse 75-77
address:      Frankfurt am Main  60329
address:      Germany

contact:      administrative
name:         Vorstand DENIC eG
organisation: DENIC eG
address:      Kaiserstrasse 75-77
address:      Frankfurt am Main  60329
address:      Germany
phone:        +49 69 27235 0
fax-no:       +49 69 27235 235
e-mail:       vorstand@denic.de

contact:      technical
name:         Business Services
organisation: DENIC eG
address:      Kaiserstrasse 75-77
address:      Frankfurt am Main  60329
address:      Germany
phone:        +49 69 27235 272
fax-no:       +49 69 27235 234
e-mail:       dbs@denic.de

nserver:      A.NIC.DE 194.0.0.53 2001:678:2:0:0:0:0:53
nserver:      F.NIC.DE 2a02:568:0:2:0:0:0:53 81.91.164.5
nserver:      L.DE.NET 2001:668:1f:11:0:0:0:105 77.67.63.105
nserver:      N.DE.NET 194.146.107.6 2001:67c:1011:1:0:0:0:53
nserver:      S.DE.NET 195.243.137.26 2003:8:14:0:0:0:0:53
nserver:      Z.NIC.DE 194.246.96.1
ds-rdata:     39227 8 2 aab73083b9ef70e4a5e94769a418ac12e887fc3c0875ef206c3451dc40b6c4fa
ds-rdata:     45580 8 2 918c32e2f12211766be6226674f447458f2259b9a0d87b44d29d55afeca6b2e1

whois:        whois.denic.de

status:       ACTIVE
remarks:      Registration information: http://www.denic.de/

created:      1986-11-05
changed:      2019-10-29
source:       IANA

% Restricted rights.
% 
% Terms and Conditions of Use
% 
% The above data may only be used within the scope of technical or
% administrative necessities of Internet operation or to remedy legal
% problems.
% The use for other purposes, in particular for advertising, is not permitted.
% 
% The DENIC whois service on port 43 doesn't disclose any information concerning
% the domain holder, general request and abuse contact.
% This information can be obtained through use of our web-based whois service
% available at the DENIC website:
% http://www.denic.de/en/domains/whois-service/web-whois.html
% 
% 

Domain: spiegel.de
Nserver: ns1.p20.dynect.net
Nserver: ns2.p20.dynect.net
Nserver: ns3.p20.dynect.net
Nserver: ns4.p20.dynect.net
Status: connect
Changed: 2019-08-21T16:57:18+02:00

**Comment by MariusMez** [comment]
Hi, I have the "same result (name= the tld only)" for the french: .fr tld

**Comment by MariusMez** [comment]
I made a PR to fix this: https://github.com/DannyCork/python-whois/pull/74

**Comment by DannyCork** [comment]
latest now returns

```
>>> data.__dict__
{'name': 'spiegel.de', 'registrar': '', 'creation_date': None, 'expiration_date': None, 'last_updated': datetime.datetime(2019, 11, 19, 18, 5, 58, tzinfo=datetime.timezone(datetime.timedelta(0, 3600))), 'name_servers': {'ns2.p20.dynect.net', 'ns1.p20.dynect.net', 'ns4.p20.dynect.net', 'ns3.p20.dynect.net'}}
```

@peet47 can you confirm please.
