### ISSUE TITLE
"before <date>" date entries aren't handled

### ISSUE THREAD

**Issue by brianosmith** [DannyCork/python-whois#75]
All .ac.uk domains generate

whois.exceptions.UnknownDateFormat: Unknown date format: 'before aug-1996'

str_to_date_py2() in _3_adjust.py needs an additional format to handle this - I suggest adding

    'before %b-%Y',                 # before aug-1996

to the DATE_FORMATS=[] definition.

**Comment by DannyCork** [comment]
An example of the issue
```
>>> domain = whois.query('cam.ac.uk')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/whois/__init__.py", line 67, in query
    return Domain(pd) if pd['domain_name'][0] else None
  File "/usr/local/lib/python3.6/dist-packages/whois/_3_adjust.py", line 14, in __init__
    self.creation_date = str_to_date(data['creation_date'][0])
  File "/usr/local/lib/python3.6/dist-packages/whois/_3_adjust.py", line 94, in str_to_date
    raise UnknownDateFormat("Unknown date format: '%s'" % text)
whois.exceptions.UnknownDateFormat: Unknown date format: 'before aug-1996'

```

**Comment by DannyCork** [comment]
master has the fix, release to follow.

Thanks @brianosmith 

```
>>> import whois
>>> domain = whois.query('cam.ac.uk')
>>> domain.__dict__
{'name': 'ac.uk', 'registrar': 'No registrar listed.  This domain is directly registered with Nominet.', 'creation_date': datetime.datetime(1996, 8, 1, 0, 0), 'expiration_date': None, 'last_updated': None, 'name_servers': {'ns0.ja.net'}}

```

**Comment by brianosmith** [comment]
Swift work @DannyCork !

So you have seen the next issue I was going to raise too: looks like UK records don't follow the format of the .com etc. fields and there are several different styles of whois response for different types of .uk domain. Thus the cam.ac.uk (and other .ac.uk) query does not return a Domain Name: (but does return a Domain:) which falls foul of the current parsing rules at __init__.py line 63 and so gets chopped down to ac.uk which does return a Domain name: but loses the specific info sought.
I don't know the full range of possibilities here, but it looks as if, on picking a few random samples, that above the TLD, .ac.uk and .gov.uk are consistent in having Domain: while .org.uk (non-profit) and .co.uk  (for profit) have Domain Name: . What's the best way to handle these - additional elif domain.endswith() calls in __init__.py ?

**Comment by brianosmith** [comment]
Having stuck in 

 ```
   elif domain.endswith('.ac.uk'):
        tld = 'ac_uk'
```
and modified tld_regexpr.py to catch this and interpret Domain: ad domain_name I hit another nasty date format
whois.exceptions.UnknownDateFormat: Unknown date format: 'monday 23rd mar 2020'
which I hacked around by adding
`    '%A %d %b %Y',                  # Tuesday 21 Jun 2011`
and
`    text = re.sub(r"(st|nd|rd|th) ", " ", text)`
before the date format conversion attempt in _3_adjust.py. This latter is a nasty hack and some better options are found here
https://stackoverflow.com/questions/1258199/python-datetime-strptime-wildcard
[](https://stackoverflow.com/questions/1258199/python-datetime-strptime-wildcard)

**Comment by brianosmith** [comment]
@DannyCork I can push you a branch with these changes in if you like.

**Comment by DannyCork** [comment]
That would be a great Christmas present @brianosmith , thanks !

**Comment by dancvrcek** [comment]
Hi, just wonder if this has been resolved. I'm still getting an error :(

`>>> import whois
>>> domain = whois.query('cam.ac.uk')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyenv3/lib/python3.7/site-packages/whois/__init__.py", line 63, in query
    return Domain(pd) if pd['domain_name'][0] else None
  File "pyenv3/lib/python3.7/site-packages/whois/_3_adjust.py", line 13, in __init__
    self.creation_date      = str_to_date(data['creation_date'][0])
  File pyenv3/lib/python3.7/site-packages/whois/_3_adjust.py", line 88, in str_to_date
    raise ValueError("Unknown date format: '%s'" % s)
ValueError: Unknown date format: 'before aug-1996'`

**Comment by DannyCork** [comment]
now working.

```
>>> domain = whois.query('cam.ac.uk')
>>> print (domain.__dict__)
{'name': 'cam.ac.uk', 'registrar': 'Jisc Services Limited', 'registrant_country': '', 'creation_date': datetime.datetime(2003, 9, 17, 0, 0), 'expiration_date': datetime.datetime(2022, 8, 13, 0, 0), 'last_updated': datetime.datetime(2020, 5, 13, 0, 0), 'status': '', 'statuses': [''], 'dnssec': False, 'name_servers': set(), 'owner': 'University of Cambridge'}
```
