### ISSUE TITLE
No expiration date for some TLDs

### ISSUE THREAD

**Issue by daghemo** [DannyCork/python-whois#82]
**Describe the bug**
The "expiration_date" is always "None" for ".com", ".net" and ".eu" domains if running with Python 2.7.5. The correct expiration date is returned for ".it", ".info", ".biz", ".io" and ".sh".

**To Reproduce**
Just run the sample code from the PyPI wih whois 0.9.5 and Python 2.7.5:

```
import whois
domain = whois.query('google.com')
print(domain.__dict__)
```

Tried on CentOS 7.x running with python-2.7.5-80 and jwhois-4.0-45.

**Comment by jasonhoward64** [comment]
Issue isn't limited to python version. I'm running 3.x and am seeing the same thing.

**Comment by DannyCork** [comment]
python 2.x is not supoprted.
