### ISSUE TITLE
Add support for .gr domains

### ISSUE THREAD

**Issue by daghemo** [DannyCork/python-whois#85]
Maybe should consider adding support for domains registered under the .gr TLD.

**Comment by WKobes** [comment]
On hold, as the .gr TLD has no whois server

```
This TLD has no whois server, but you can access the whois database at
https://grweb.ics.forth.gr/public/whois
```

**Comment by maarten-boot** [comment]
can be closed:
implemented: gr = {"extend": "_privateReg"}
