### ISSUE TITLE
More "not found" cases required in parsing

### ISSUE THREAD

**Issue by brianosmith** [DannyCork/python-whois#89]
Querying an fully qualified name that contains a valid domain name can fail due to the variety of responses that the whois server may return.

For example

```
>whois cryst.bbk.ac.uk

No such domain cryst.bbk.ac.uk
```

and

```
>whois mail.google.com
No match for "MAIL.GOOGLE.COM".
>>> Last update of whois database: 2020-01-09T12:34:54Z <<<

NOTICE: The expiration date displayed in this record is the date the
registrar's sponsorship of the domain name registration in the registry is
currently set to expire. This date does not necessarily reflect the expiration
date of the domain name registrant's agreement with the sponsoring
registrar.  Users may consult the sponsoring registrar's Whois database to
view the registrar's reported ....

```

**Expected behavior**
The supplied address should be trimmed until a valid domain is fed to whois.

This seems to be the intended behaviour of the while: at the end of __init__.py, but relied on catching lookup failures in do_parse() which currently only catches "not found" and "error".

**Example**

`>>> checkMGC = whois.query('mail.cam.ac.uk')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/whois/__init__.py", line 64, in query
    pd = do_parse(do_query(d, force, cache_file, slow_down, ignore_returncode), tld)
  File "/usr/lib/python2.7/site-packages/whois/_2_parse.py", line 40, in do_parse
    raise FailedParsingWhoisOutput(whois_str)
whois.exceptions.FailedParsingWhoisOutput: 
No such domain mail.cam.ac.uk
`

**Comment by DannyCork** [comment]
[>>> domain = whois.query('cryst.bbk.ac.uk')
>>> print (domain.__dict__)
{'name': 'bbk.ac.uk', 'registrar': 'Jisc Services Limited', 'registrant_country': '', 'creation_date': datetime.datetime(2003, 9, 17, 0, 0), 'expiration_date': datetime.datetime(2021, 9, 21, 0, 0), 'last_updated': datetime.datetime(2019, 6, 21, 0, 0), 'status': '', 'statuses': [''], 'dnssec': False, 'name_servers': set(), 'owner': 'Birkbeck College'}](url)
