### ISSUE TITLE
missing date format for .de

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DannyCork/python-whois#9]
```
What steps will reproduce the problem?
1. check expiration date of domain (fraukesart.de)

What do you see instead?

ValueError: Unknown date format: '2013-01-25t06:14:54+0100'

What version of the product are you using? On what operating system?
0.7 from pypi @debian wheezy






```

Original issue reported on code.google.com by `ma...@whitehats.pl` on 19 Apr 2013 at 1:01

**Comment by DannyCork** [comment]
This is the whois 0.8 query output 
`{
	'name': 'de',
	'registrar': '',
	'creation_date': None,
	'expiration_date': None,
	'last_updated': datetime.datetime(2018, 1, 16, 0, 0),
	'name_servers': {
		'z.nic.de',
		'us-dns.venus.orderbox-dns.com',
		'us-dns.earth.orderbox-dns.com',
		'us-dns.mercury.orderbox-dns.com',
		'us-dns.mars.orderbox-dns.com',
		's.de.net',
		'a.nic.de',
		'l.de.net',
		'f.nic.de',
		'n.de.net'
	}
}`

compared to the output from the command line whois
`
% IANA WHOIS server
% for more information on IANA, visit http://www.iana.org
% This query returned 1 object

refer:        whois.denic.de

domain:       DE

organisation: DENIC eG
address:      Kaiserstrasse 75-77
address:      Frankfurt am Main  60329
address:      Germany

contact:      administrative
name:         Vorstand DENIC eG
organisation: DENIC eG
address:      Kaiserstrasse 75-77
address:      Frankfurt am Main  60329
address:      Germany
phone:        +49 69 27235 0
fax-no:       +49 69 27235 235
e-mail:       vorstand@denic.de

contact:      technical
name:         Business Services
organisation: DENIC eG
address:      Kaiserstrasse 75-77
address:      Frankfurt am Main  60329
address:      Germany
phone:        +49 69 27235 272
fax-no:       +49 69 27235 234
e-mail:       dbs@denic.de

nserver:      A.NIC.DE 194.0.0.53 2001:678:2:0:0:0:0:53
nserver:      F.NIC.DE 2a02:568:0:2:0:0:0:53 81.91.164.5
nserver:      L.DE.NET 2001:668:1f:11:0:0:0:105 77.67.63.105
nserver:      N.DE.NET 194.146.107.6 2001:67c:1011:1:0:0:0:53
nserver:      S.DE.NET 195.243.137.26 2003:8:14:0:0:0:0:53
nserver:      Z.NIC.DE 194.246.96.1
ds-rdata:     39227 8 2 aab73083b9ef70e4a5e94769a418ac12e887fc3c0875ef206c3451dc40b6c4fa

whois:        whois.denic.de

status:       ACTIVE
remarks:      Registration information: http://www.denic.de/

created:      1986-11-05
changed:      2018-01-16
source:       IANA

% Restricted rights.
%
% Terms and Conditions of Use
%
% The above data may only be used within the scope of technical or
% administrative necessities of Internet operation or to remedy legal
% problems.
% The use for other purposes, in particular for advertising, is not permitted.
%
% The DENIC whois service on port 43 doesn't disclose any information concerning
% the domain holder, general request and abuse contact.
% This information can be obtained through use of our web-based whois service
% available at the DENIC website:
% http://www.denic.de/en/domains/whois-service/web-whois.html
%
%

Domain: fraukesart.de
Nserver: us-dns.earth.orderbox-dns.com
Nserver: us-dns.mars.orderbox-dns.com
Nserver: us-dns.mercury.orderbox-dns.com
Nserver: us-dns.venus.orderbox-dns.com
Status: connect
Changed: 2018-06-14T12:07:03+02:00`

**Comment by DannyCork** [comment]
still an issue for .de
```
>>> domain = whois.query('fraukesart.de')
>>> print(domain.__dict__)
{'name': 'fraukesart.de', 'registrar': '', 'registrant_country': '', 'creation_date': None, 'expiration_date': None, 'last_updated': None, 'status': 'free', 'statuses': ['free'], 'dnssec': False, 'name_servers': set()}
```

**Comment by maarten-boot** [comment]
this particular domain is now free; fraukesart.de

**Comment by maarten-boot** [comment]
i expect this issue also can be closed now that status: free returns None instead of trying to parse the incomplete output
