### ISSUE TITLE
Add support for .ua TLD

### ISSUE THREAD

**Issue by annaelizabeth** [DannyCork/python-whois#99]
Add support for Ukraine ccTLD .ua

**Comment by DannyCork** [comment]
{'name': 'yandex.ua', 'registrar': 'ua.imena', 'registrant_country': 'UA', 'creation_date': datetime.datetime(2005, 4, 27, 0, 54, 19), 'expiration_date': datetime.datetime(2025, 4, 27, 0, 54, 19), 'last_updated': datetime.datetime(2017, 5, 24, 19, 35, 30), 'status': 'ok', 'statuses': ['ok', 'linked'], 'dnssec': False, 'name_servers': {'ns7.yandex.ru', 'ns8.yandex.ru'}}
